In [15]:
# Installing numpy package if it's not already installed
!pip install numpy

 

In [16]:
# Importing numpy with an alias for ease of use
import numpy as np

    

In [18]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [25]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
print(f"My array has the shape of (rows , cols) {array_2d.shape}")

2D Array:
 [[1 2 3]
 [4 5 6]]
My array has the shape of (rows , cols) (2, 3)


In [29]:
# Array attributes
array = np.array([[10, 20, 30], [40, 50, 60]])
print("Array shape:", array.shape)
print("Array dimensions:", array.ndim)
print("Array size:", array.size)
print("Array data type:", array.dtype)


Array shape: (2, 3)
Array dimensions: 2
Array size: 6
Array data type: int64


In [33]:
# Initializing arrays with zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:\n", zeros_array)

# Initializing arrays with ones
ones_array = np.ones((2, 4))
print("Ones Array:\n", ones_array)

# # Initializing arrays with a specific value
full_array = np.full((5, 5), 100)
print("Full Array:\n", full_array)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [42]:
# Creating an array with a range of values
range_array = np.arange(0, 10000, 2) # even value 
print("Range Array:", range_array)

# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 10, 5)
print("Linspace Array:", linspace_array)


Range Array: [   0    2    4 ... 9994 9996 9998]
Linspace Array: [ 0.   2.5  5.   7.5 10. ]


In [46]:
# Creating an array with random values
random_array = np.random.random((100, 100))
print("Random Array:\n", random_array)

# # Creating an array with random integers
randint_array = np.random.randint(1, 10, (100, 100))
print("Random Integer Array:\n", randint_array)


Random Array:
 [[0.96639874 0.68009461 0.1171127  ... 0.77445491 0.2828917  0.16063674]
 [0.45536222 0.3477264  0.47290625 ... 0.83929706 0.57193268 0.11388858]
 [0.21797235 0.76343062 0.4958449  ... 0.61960987 0.89614608 0.87991268]
 ...
 [0.72919871 0.10324731 0.85157366 ... 0.77062916 0.79352027 0.48754011]
 [0.07491631 0.80243331 0.28103515 ... 0.50518398 0.75570171 0.61078435]
 [0.93676198 0.06058074 0.25833093 ... 0.94079853 0.41609879 0.46205743]]
Random Integer Array:
 [[8 6 2 ... 3 9 7]
 [4 8 3 ... 3 7 9]
 [8 2 7 ... 4 3 4]
 ...
 [3 7 2 ... 1 3 9]
 [8 5 9 ... 2 6 7]
 [7 3 2 ... 3 3 1]]


In [52]:
# Accessing elements in a 1D array
# array = np.array([1, 2, 3, 4, 5])
# print("Element at index 0:", array[0])
# print("Element at index 3:", array[3])


my_2d_list = [[1, 2, 3],
              [4, 5, 6]]

print(f"Accessomg elemnts in my 2D list {my_2d_list[1][1]}")

# Accessing elements in a 2D array
# array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 0, column 1:", array_2d[0, 1])
print("Element at row 1, column 2:", array_2d[1, 1])



Accessomg elemnts in my 2D list 5
Element at row 0, column 1: 2
Element at row 1, column 2: 5


In [59]:
# Reshaping a 1D array to a 2D array
array = np.array([1, 2, 3, 4, 5, 6])
print(array.shape)
reshaped_array = array.reshape((2, 3))
print("Reshaped Array:\n", reshaped_array)
print(reshaped_array.shape)


# Flattening a 2D array to a 1D array
flattened_array = reshaped_array.flatten()
print("Flattened Array:", flattened_array)
print(flattened_array.shape)

(6,)
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
(2, 3)
Flattened Array: [1 2 3 4 5 6]
(6,)


In [61]:
# Concatenating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate((array1, array2))
print("Concatenated Array:", concatenated_array)

# Concatenating two 2D arrays along rows
array1_2d = np.array([[1, 2], [3, 4]])
array2_2d = np.array([[5, 6], [7, 8]])
concatenated_array_2d = np.concatenate((array1_2d, array2_2d), axis=0)
print("Concatenated 2D Array along rows:\n", concatenated_array_2d)

# Concatenating two 2D arrays along columns
concatenated_array_2d_col = np.concatenate((array1_2d, array2_2d), axis=1)
print("Concatenated 2D Array along columns:\n", concatenated_array_2d_col)


Concatenated Array: [1 2 3 4 5 6]
Concatenated 2D Array along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [71]:
# Statistical functions
array = np.array([1, 2, 3, 4, 5,6,7,8,9])

# Manually calculate the mean!
python_sum = 0
count = 0 
for i in array:
    python_sum = python_sum + i
    count += 1
print(python_sum , count)
manual_mean = python_sum / count  
print(f"The mean calculated manually is {manual_mean}")

# Mean
mean = np.mean(array)
print(f"The mean calculated automatically is {mean}")

# Median
median = np.median(array)
print("Median:", median)

# Standard deviation
std_dev = np.std(array)
print("Standard Deviation:", std_dev)



45 9
The mean calculated manually is 5.0
The mean calculated automatically is 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
